from Crypto.Cipher import AES
import base64

msg_text = """'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
ECCCCCCCCCCCCCCCCCGCCCCCCCPOPCS
PCPPPPPPPPPPPPPPPPPPPPPPPPPCPCP
PCCCCCCCCCCCOCCCCCCCCCCCCCPCPCP
PCPPPPPPPPPPPPPPPPPPPPPPPPPCPCP
PCCCCCCCCCCCGCCCCCCCCCCCCCPOPCP
PCPPPPPPPPPPPPPPPPPPPPPPPPPCPCP
PCCCCCCCCCCCCCCCCCCCCCCCCCPOPCP
PCPPPPPPPPPPPPPPPPPPPPPPPCPCPCP
PCCCCCCCCCCCCCCCCCCCCCCCPCPOPCP
PCPPPPPPPPPPPPPPPPPPPPPPPCPCPCP
PCCCCCCCOCCCCCCCCCCCCCCCPCPOPCP
PCPPPPPPPPPPPPPPPPPPPPPPPCPPPCP
PCCCCCCCCCCCCCGCCCCCKCCCPCCCCCP
PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP'""".rjust(1024)
secret_key = '1234567890123456'.encode() # create new & store somewhere safe

cipher = AES.new(secret_key,AES.MODE_ECB) # never use ECB in strong systems obviously
encoded = base64.b64encode(cipher.encrypt(msg_text.encode()))
# ...
decoded = cipher.decrypt(base64.b64decode(encoded))
print("crypt: ", encoded)
print ("desencrip: ",decoded.strip())